---

- ansible.builtin.import_tasks: userconfig.yml
  name: userconfig
- ansible.builtin.import_tasks: base.yml
  name: base
- ansible.builtin.import_tasks: ntp.yml
  name: ntp
  when: system.use_ntp == true
- ansible.builtin.import_tasks: locale.yml
  name: locale
