---

# Note: In recent Arch version default algorithm
# has been changed to the YESCRYPT. However, the integration
# is still buggy. trying to change the password leads to the error
# and fallback to the DES hashing. Updating pam / libxcrypt didn't help.
# TODO: verify whether hashing was fixed
- name: Change password hashing algorithm to SHA512
  shell: |
    sed -i "s/ENCRYPT_METHOD YESCRYPT/ENCRYPT_METHOD SHA512/" /etc/login.defs

- name: Ensure group user.group exists
  group:
    name: "{{ user.group }}"
    state: present
  when: user.name is defined

- name: Ensure the user user.name exists
  user:
    name: "{{ user.name }}"
    shell: "{{ user.shell }}"
    groups:
      - "{{ user.group }}"
      - wheel
      - network
      - lock
      - uucp
    append: true
    system: false
    createhome: true
    home: /home/{{ user.name }}
  when: user.name is defined

- name: Ensure user directories exist
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "/home/{{ user.name }}/Documents"
    - "/home/{{ user.name }}/Screenshots"
    - "/home/{{ user.name }}/Downloads"
    - "/home/{{ user.name }}/repos"
    - "/home/{{ user.name }}/.ssh"

- name: Add user to the sudoers group
  lineinfile:
    dest: /etc/sudoers
    state: present
    line: "{{ user.name }} ALL=(ALL) ALL"

