---

- name: install i3 windowmanager and components
  pacman:
    name:
      - xorg
      - xorg-xinit
      - i3-gaps
      - i3lock
      - i3status-rust
      - dmenu
      - feh
      - dunst
      - rofi
      - picom
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

# TODO: fix configure the i3lock fancy
# TODO: configure shortcuts for rofi-power-menu
# Verified: 20.10.2023
- name: install i3lock fancy from aur
  kewlfft.aur.aur:
    name: "{{ item }}"
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
  with_items:
    - i3lock-fancy-dualmonitors-git
    # - glitchlock
    - rofi-power-menu
  become_user: aur_builder

- name: create i3wm configuration directory and util subdirectory
  ansible.builtin.file:
    name: /home/{{ user.name }}/.i3/util
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.group }}"

- name: copy X11 config
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /etc/X11/xorg.conf.d/
    owner: root
    group: root
  with_items:
    - 00-keyboard.conf
    - 50-mouse-acceleration.conf
    - 50-mouse-deceleration.conf
