---

- name: install vim
  pacman:
    name: vim
    state: present

- name: Ensure vim autoload dir exists
  file: 
    path: "/home/{{ user.name }}/.vim/autoload"
    state: directory

- name: Install VimPlug plugin manager
  copy:
    src: plug.vim
    dest: "/home/{{ user.name }}/.vim/autoload/plug.vim"

- name: Install vim plugins
  command: "vim +'PlugInstall --sync' +qa"

- name: install gruvbox theme
  kewlfft.aur.aur:
    name: vim-gruvbox-git
  become_user: aur_builder
  become: true

- name: install vscodium
  kewlfft.aur.aur:
    name: vscodium-bin
  become_user: aur_builder
  become: true

- name: install vscodium extensions
  command: "vscodium --install-extension {{ item }}"
  become_user: "{{ user.name }}"
  register: ext_install
  changed_when: ext_install.rc != 0
  with_items:
    - asciidoctor.asciidoctor-vscode
    - gulajavaministudio.mayukaithemevsc
    - k--kato.intellij-idea-keybindings
    - ms-python.python
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
    - rebornix.ruby
    - redhat.java
    - redhat.vscode-yaml
    - streetsidesoftware.code-spell-checker
    - waderyan.gitblame
    - wingrunr21.vscode-ruby
