# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    # Pull official archlinux box
    config.vm.box = "archlinux/archlinux"

    # Enable synced folders to sync the playbook to the virtual machine using rsync
    config.vm.synced_folder "../ansible", "/vagrant", type: "rsync", rsync__auto: "true"

#    config.vm.provision "shell" do |s|
      #s.inline = <<-SHELL
        #ansible-galaxy install -r /vagrant/requirements.yml 
      #SHELL
#    end

    # Configure the vagrant provisioner to use a local ansible connection
    config.vm.provision "ansible_local" do |ansible|
        ansible.verbose = "v"
        ansible.limit = "all"
        ansible.inventory_path = "/vagrant/inventory/all.yml"
        ansible.galaxy_role_file = "/vagrant/requirements.yml"
        #ansible.galaxy_command = "ansible-galaxy install -r /vagrant/requirements.yml"
        ansible.playbook = "/vagrant/playbook.yml"
    end

    # Customize the vm configs
    config.vm.provider "virtualbox" do |vb|
        # Add an optical drive to install guest additions
        vb.customize ["storageattach", :id,
                      "--storagectl", "IDE Controller",
                      "--port", "0", "--device", "1",
                      "--type", "dvddrive",
                      "--medium", "emptydrive"]
        # increase virtual video ram
        vb.customize ["modifyvm", :id, "--vram", "128"]
        vb.cpus = "2"
        vb.memory = "6192"
    end
end
