---

- name: Install gimp
  pacman:
    name:
      - gimp
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

# Other packages might be worth considering
# for photo editing
# - darktable
# - rawtherapee
# - shotwell

- name: Install flameshot
  pacman: 
    name: flameshot
    state: present