---
- name: Install telegram
  pacman:
    name: telegram-desktop
    state: present
  when: messengers.install_telegram | bool

- name: Install Slack
  kewlfft.aur.aur:
    name: slack-desktop
    state: present
  become_user: aur_builder
  when: messengers.install_slack | bool