---

- name: Install rcm
  kewlfft.aur.aur:
    name: rcm
  become: true
  become_user: aur_builder
  register: task_result
  until: task_result is success
  retries: 3
  delay: 2
  when: dotfiles.installation == "true"
  tags:
    - aur

- name: Clone user dotfiles
  git:
    repo: "{{ dotfiles.url }}"
    dest: /home/{{ user.name }}/{{ dotfiles.destination }}
    accept_hostkey: true
    update: true
    force: true
  when: dotfiles.installation == "true"
  become: true
  become_user: "{{ user.name }}"

- name: Install user dotfiles
  command: "rcup -d /home/{{ user.name }}/{{ dotfiles.destination }} {{ dotfiles.rcup_flags }}"
  when: dotfiles.installation == "true"
  become: true
  become_user: "{{ user.name }}"
