---
# TODO: DNS over TLS / over HTTPS by default
- name: Setup DNS server for systemd-resolved
  shell: |
    sed -i "s/#DNS=/DNS=1.1.1.1/" /etc/systemd/resolved.conf
    systemctl restart systemd-resolved
- name: Install network tools
  ansible.builtin.package:
    name:
      - ethtool
      - wpa_supplicant
      - netctl
      - dhcpcd
      - nmap
      # Fuck network manager
      # - networkmanager
      # - network-manager-applet
      # - networkmanager-openconnect
      # - networkmanager-openvpn
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
  # TODO remove
  # notify:
  #   - rkhunter propupdate
- name: Enable dhcp service
  service: name=dhcpcd state=started enabled=true
# Fuck network manager
# - name: Enable NetworkManager service
#   service:
#     name: NetworkManager
#     state: started
#     enabled: true
