---

- name: Install RedShift and dependencies
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - librsvg
    - python-gobject
    - python-xdg
    - redshift
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

# - name: Enable avahi daemon
#   ansible.builtin.service:
#     name: avahi-daemon
#     state: started
#     enabled: true
