---

- name: Install alsa-utils and pulseaudio tools
  pacman:
    name:
      - alsa-utils
      - pulseaudio
      - pulseaudio-alsa
      - pavucontrol
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: create directory for pulse
  ansible.builtin.file:
    path: "/home/{{ user.name }}/.config/pulse"
    state: directory
    owner: "{{ user.name }}"

- name: Deploy HiFi pulse audio daemon configuration
  ansible.builtin.template:
    src: daemon.conf.j2
    dest: "/home/{{ user.name }}/.config/pulse/daemon.conf"
  become_user: "{{ user.name }}"
  become: true

- name: Add user to the audio group
  user:
    name: "{{ user.name }}"
    group: audio
    append: true