---

- name: Install secure arch linux environment
  hosts: arch_workstation
  connection: local
  become: true

  roles:
    - { role: network, tags: ['network'] }
    # See https://wiki.archlinux.org/title/Security#Kernel_hardening
    # Warning: Conflicts with virtualbox-guest. Hardened headers are yet
    # to be tested. Potentially might cause problems on arch host like
    # https://bbs.archlinux.org/viewtopic.php?id=255637
    # - { role: kernel, tags: ['kernel'] }
    
    # Bootloader is already configured in the archlinux VM
    # TODO: back to the separation between syslinux and grub role
    # Optionally include role based on the tag.
    # - { role: bootloader, tags: ['grub']}  
    - { role: grub, tags: ['grub']}
    - { role: syslinux, tags: ['syslinux']}

    - { role: base, tags: ['base'] }
   
    - { role: dotfiles, tags: ['dotfiles'] }
    - { role: shell, tags: ['shell'] }
    - { role: editor, tags: ['editor'] }
    - { role: terminal, tags: ['terminal'] }
    - { role: windowmanager, tags: ['windowmanager'] }
    - { role: browsers, tags: ['browsers'] }
    - { role: bluetooth, tags: ['bluetooth'] }
    - { role: messengers, tags: ['messengers'] }
    - { role: keepass, tags: ['keepass'] }
    
    - { role: macspoof, tags: ['macspoof'], when: "system.macspoof == 'enabled'"}
    - { role: redshift, tags: ['redshift'] }
    - { role: sound, tags: ['sound'] }
    - { role: mail, tags: ['mail'] }
    - { role: photography,d tags: ['photography'] }
    - { role: calibre, tags: ['calibre'] }


    - { role: virtualbox-guest, tags: ['virtualbox-guest'] }

    - { role: dev, tags: ['dev'] }

    # Spotify is not frequently used as for now
    # - { role: spotify, tags: ['spotify'] }

    # Fix required
    # - { role: firewall, tags: ['firewall'] }
