---

- name: install urxvt terminal emulator
  pacman:
    name: rxvt-unicode
    state: present
  register: task_result
  until: task_result is success
  retries: 2
  delay: 2
  when: terminal.install_urxvt | bool

- name: install alacritty terminal emulator
  pacman:
    name: "alacritty"
    state: present
  register: task_result
  until: task_result is success
  retries: 2
  delay: 2
  when: terminal.install_alacritty | bool

- name: install kitty terminal emulator
  pacman:
    name: kitty
    state: present
  register: task_result
  until: task_result is success
  retries: 2
  delay: 2
  when: terminal.install_kitty | bool

- name: install tmux terminal multiplexer
  pacman:
    name: tmux
    state: present
  register: task_result
  until: task_result is success
  retries: 2
  delay: 2
